import { useEffect } from 'react';

import {
  useBotFormState,
  type Fields,
} from '@/contexts/bots/form/BotFormProvider';

interface UseAutoNameFromPresetArgs {
  /** 'create' | 'edit' — only auto-fill in create mode. */
  mode: string;
  /** First pair in the bot's pair list (used as the name prefix). */
  firstPair: string;
  /**
   * Number of pairs selected. When > 1 the prefix becomes
   * `{firstPair} +{n-1}` (e.g. `BTCUSDT +4`) to signal a multi-pair bot.
   * Defaults to 1 (single pair). Only DCA Quick mode ever passes > 1.
   */
  pairCount?: number;
  /** The currently-active preset (provides the suffix label, when set). */
  activePreset: { label: string } | null | undefined;
  /**
   * All preset labels in this bot type's catalog. Used to detect names
   * that look auto-generated so we don't clobber user-typed names.
   */
  presetLabels: ReadonlyArray<string>;
  /**
   * Bot type label used as the middle segment when no preset is active
   * (e.g. 'DCA', 'Combo', 'Grid'). Ensures the name is meaningful even
   * before the user picks a strategy preset.
   */
  botTypeLabel: string;
}

/** Escape a label so it can be embedded safely inside a RegExp. */
const escapeRegExp = (value: string): string =>
  value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Local calendar date as `YYYY-MM-DD` (ISO date, no time component). */
const todayIso = (): string => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

/**
 * Auto-fills `formData.name` with `{prefix} {preset|botType} {date}` —
 * using the active preset label when one is selected, otherwise the bot
 * type label, and always appending today's ISO date. The prefix is the
 * first pair, or `{firstPair} +{n-1}` when several pairs are selected.
 * E.g. `BTCUSDT Conservative 2026-07-01`, `BTCUSDT DCA 2026-07-01`, or
 * `BTCUSDT +4 Mid-term 2026-07-01`.
 *
 * Only overwrites names that are empty, the bare `New Bot` default, or a
 * value we previously auto-generated (any name ending in a known label
 * followed by an ISO date, or a legacy `{pair} {presetLabel}` name). If
 * the user has typed something else, the name is left alone.
 */
export const useAutoNameFromPreset = ({
  mode,
  firstPair,
  pairCount = 1,
  activePreset,
  presetLabels,
  botTypeLabel,
}: UseAutoNameFromPresetArgs): void => {
  const { formData, updateFormData } = useBotFormState();

  useEffect(() => {
    if (mode !== 'create') return;
    if (!firstPair) return;
    const currentName = (formData.name ?? '').trim();

    const prefix = pairCount > 1 ? `${firstPair} +${pairCount - 1}` : firstPair;
    const middle = activePreset?.label ?? botTypeLabel;
    const next = `${prefix} ${middle} ${todayIso()}`;
    if (next === currentName) return;

    const knownLabels = [...presetLabels, botTypeLabel];
    const looksAutoGenerated =
      !currentName ||
      currentName === 'New Bot' ||
      knownLabels.some((label) =>
        new RegExp(`\\s${escapeRegExp(label)}\\s\\d{4}-\\d{2}-\\d{2}$`).test(
          currentName
        )
      ) ||
      // Legacy "{pair} {presetLabel}" names (before dates were appended).
      presetLabels.some((label) => currentName.endsWith(` ${label}`));
    if (!looksAutoGenerated) return;

    updateFormData('name' as Fields, next);
  }, [
    activePreset,
    firstPair,
    pairCount,
    mode,
    formData.name,
    presetLabels,
    botTypeLabel,
    updateFormData,
  ]);
};
