import { useEffect } from 'react';

import {
  useBotFormState,
  type Fields,
} from '@/contexts/bots/form/BotFormProvider';

interface UseAutoNameFromPresetArgs {
  /** 'create' | 'edit' — only auto-fill in create mode. */
  mode: string;
  /** First pair in the bot's pair list (used as the name prefix). */
  firstPair: string;
  /** The currently-active preset (provides the suffix label). */
  activePreset: { label: string } | null | undefined;
  /**
   * All preset labels in this bot type's catalog. Used to detect names
   * that look auto-generated so we don't clobber user-typed names.
   */
  presetLabels: ReadonlyArray<string>;
}

/**
 * Auto-fills `formData.name` from `firstPair + activePreset.label` when
 * the name field is empty or still holds a previously auto-generated
 * value (any name ending with " <preset.label>" for one of the known
 * presets). If the user has typed something else, the name is left
 * alone.
 */
export const useAutoNameFromPreset = ({
  mode,
  firstPair,
  activePreset,
  presetLabels,
}: UseAutoNameFromPresetArgs): void => {
  const { formData, updateFormData } = useBotFormState();

  useEffect(() => {
    if (mode !== 'create') return;
    if (!firstPair || !activePreset) return;
    const currentName = (formData.name ?? '').trim();
    const looksAutoGenerated =
      !currentName ||
      presetLabels.some((label) => currentName.endsWith(` ${label}`));
    if (!looksAutoGenerated) return;
    const next = `${firstPair} ${activePreset.label}`;
    if (next !== currentName) {
      updateFormData('name' as Fields, next);
    }
  }, [
    activePreset,
    firstPair,
    mode,
    formData.name,
    presetLabels,
    updateFormData,
  ]);
};
