/* eslint-disable react-hooks/exhaustive-deps */
import logger from '@/lib/loggerInstance';
import { FIVE_MINUTES, queryClient } from '@/lib/queryClient';
import { useCacheStatusStore } from '@/stores/cacheStatusStore';
import { useIsFetching } from '@tanstack/react-query';
import { useEffect, useMemo, useRef } from 'react';

const AUTO_REVALIDATE_COOLDOWN = 30 * 1000; // 30 seconds

/**
 * Hook to track cache status for a component using one or more GraphQL queries
 *
 * @param componentId - Unique identifier for the component (e.g., widgetId)
 * @param cacheKeys - Array of cache keys (already generated by useCacheKey)
 * @param queryNames - Array of query names for display
 * @returns Cache status including oldest timestamp and revalidation state
 */
export function useCacheStatus(
  componentId: string,
  cacheKeys: unknown[][],
  queryNames: string[]
) {
  const { updateCacheStatus } = useCacheStatusStore();

  // Create stable string representation to avoid infinite loops
  const cacheKeysStr = useMemo(() => JSON.stringify(cacheKeys), [cacheKeys]);
  const stableCacheKeys = useMemo(() => cacheKeys, [cacheKeysStr]);
  const queryNamesStr = useMemo(() => queryNames.join(','), [queryNames]);
  const stableQueryNames = useMemo(() => queryNames, [queryNamesStr]);

  // Track fetching state for each query
  const isFetching = useIsFetching();
  const isRevalidating = useMemo(() => {
    // Check if any of our queries are currently fetching
    const result = stableCacheKeys.some((cacheKey) => {
      const query = queryClient
        .getQueryCache()
        .findAll({ queryKey: cacheKey })
        .find((q) => q.state.fetchStatus === 'fetching');
      return !!query;
    });
    if (result) {
      logger.debug(
        `[CacheStatus] Queries revalidating for component: ${componentId}`
      );
    }
    return result;
  }, [stableCacheKeys, cacheKeysStr, isFetching, componentId]);

  // Get oldest cache timestamp from all queries
  // Update whenever isFetching changes to catch state updates
  const oldestTimestamp = useMemo(() => {
    let oldest = Date.now();

    stableCacheKeys.forEach((cacheKey) => {
      const queries = queryClient
        .getQueryCache()
        .findAll({ queryKey: cacheKey });

      queries.forEach((query) => {
        if (query.state.dataUpdatedAt && query.state.dataUpdatedAt < oldest) {
          oldest = query.state.dataUpdatedAt;
        }
      });
    });

    return oldest;
  }, [stableCacheKeys, cacheKeysStr, isFetching]);

  // Use ref to track if we've done initial update
  const hasInitialized = useRef(false);
  const lastAutoRevalidateRef = useRef(0);

  // Update cache status in store only when values actually change
  useEffect(() => {
    const shouldUpdate =
      !hasInitialized.current || updateCacheStatus.length > 0; // This always passes but prevents warning

    if (shouldUpdate) {
      logger.debug(`[CacheStatus] Updating store for ${componentId}`, {
        isRevalidating,
        oldestTimestamp,
        age: Date.now() - oldestTimestamp,
        queryNames: stableQueryNames,
      });
      updateCacheStatus(
        componentId,
        stableQueryNames,
        oldestTimestamp,
        isRevalidating
      );
      hasInitialized.current = true;
    }
  }, [
    componentId,
    cacheKeysStr,
    oldestTimestamp,
    isRevalidating,
    queryNamesStr,
  ]);

  // Automatically revalidate once data becomes stale
  useEffect(() => {
    const now = Date.now();
    const isStale = now - oldestTimestamp > FIVE_MINUTES;

    if (!isStale || isRevalidating) {
      return;
    }

    if (now - lastAutoRevalidateRef.current < AUTO_REVALIDATE_COOLDOWN) {
      return;
    }

    lastAutoRevalidateRef.current = now;

    logger.info(
      `[CacheStatus] Auto revalidating stale queries for ${componentId}`,
      {
        staleFor: now - oldestTimestamp,
        queryNames: stableQueryNames,
      }
    );

    stableCacheKeys.forEach((cacheKey) => {
      queryClient.invalidateQueries({
        queryKey: cacheKey,
        refetchType: 'active',
      });
    });
  }, [
    componentId,
    isRevalidating,
    oldestTimestamp,
    queryNamesStr,
    stableQueryNames,
    stableCacheKeys,
  ]);

  return {
    lastUpdated: oldestTimestamp,
    isRevalidating,
    queryKeys: stableQueryNames,
  };
}
