import {
  BaseSlOnEnum,
  BotMarginTypeEnum,
  BotStartTypeEnum,
  CloseConditionEnum,
  CloseDCATypeEnum,
  ComboTpBase,
  CooldownOptionsEnum,
  CooldownUnits,
  DCAConditionEnum,
  DCATypeEnum,
  DcaVolumeRequiredChangeRef,
  DCAVolumeType,
  DynamicPriceFilterDirectionEnum,
  DynamicPriceFilterPriceTypeEnum,
  FuturesStrategyEnum,
  IndicatorsLogicEnum,
  IndicatorStartConditionEnum,
  InitialPriceFromEnum,
  OrderSizeTypeEnum,
  OrderTypeEnum,
  PairPrioritizationEnum,
  RiskSlTypeEnum,
  RRSlTypeEnum,
  ScaleDcaTypeEnum,
  StartConditionEnum,
  StrategyEnum,
  TerminalDealTypeEnum,
  VolumeValueEnum,
} from '@/types';
import type { BotFormData } from '@/types/bots/form';

export const SHARED_FORM_DEFAULTS: Readonly<
  Required<Omit<BotFormData, 'dca' | 'combo' | 'grid' | 'type' | 'originalBot'>>
> = {
  exchangeUUID: '',
  pairMetadata: {},
  pairPrecisionMap: {},
  userFee: null,
  favoriteIndicators: [],
  pair: ['BTCUSDT'],
  name: 'New Bot',
  orderSizeReference: 'notional',
  initialPrice: '',
  initialPriceFrom: InitialPriceFromEnum.start,
  askToReset: false,
  dcaOrderGuard: null,
  terminal: false,
};

export const DCA_FORM_DEFAULTS: Readonly<Required<BotFormData['dca']>> = {
  strategy: StrategyEnum.long,
  profitCurrency: 'quote',
  baseOrderSize: '10',
  startOrderType: OrderTypeEnum.limit,
  startCondition: StartConditionEnum.asap,
  tpPerc: '1',
  orderFixedIn: 'quote',
  orderSize: '10',
  step: '1',
  gridLevel: '5',
  comboSmartGridsCount: '6',
  ordersCount: '5',
  activeOrdersCount: '1',
  volumeScale: '1',
  stepScale: '1',
  useTp: true,
  useSl: false,
  slPerc: '-10',
  baseSlOn: BaseSlOnEnum.avg,
  useSmartOrders: false,
  minOpenDeal: '',
  maxOpenDeal: '',
  useDca: true,
  hodlDay: '7',
  hodlAt: '15:00',
  hodlNextBuy: new Date(new Date().setHours(24, 0, 0, 0)).getTime(),
  maxNumberOfOpenDeals: '1',
  indicators: [],
  indicatorGroups: [],
  orderSizeType: OrderSizeTypeEnum.quote,
  limitTimeout: '20',
  useLimitTimeout: false,
  cooldownAfterDealStart: false,
  cooldownAfterDealStartInterval: 1,
  cooldownAfterDealStartUnits: CooldownUnits.minutes,
  cooldownAfterDealStartOption: CooldownOptionsEnum.bot,
  cooldownAfterDealStop: false,
  cooldownAfterDealStopInterval: 1,
  cooldownAfterDealStopUnits: CooldownUnits.minutes,
  cooldownAfterDealStopOption: CooldownOptionsEnum.bot,
  moveSL: false,
  moveSLTrigger: '0.5',
  moveSLValue: '0.2',
  moveSLForAll: true,
  trailingSl: false,
  trailingTp: false,
  trailingTpPerc: '0.3',
  useCloseAfterX: false,
  closeAfterX: '20',
  useCloseAfterXloss: false,
  closeAfterXloss: '20',
  useCloseAfterXprofit: false,
  closeAfterXprofitCond: IndicatorStartConditionEnum.gt,
  closeAfterXprofitValue: '20',
  useCloseAfterXwin: false,
  closeAfterXwin: '20',
  useMulti: false,
  maxDealsPerPair: '1',
  useCloseAfterXopen: false,
  closeAfterXopen: '20',
  botStart: BotStartTypeEnum.manual,
  botActualStart: BotStartTypeEnum.manual,
  useBotController: false,
  stopType: CloseDCATypeEnum.leave,
  dealCloseCondition: CloseConditionEnum.tp,
  dealCloseConditionSL: CloseConditionEnum.tp,
  useMinTP: false,
  minTp: '1',
  closeDealType: CloseDCATypeEnum.closeByMarket,
  useMultiTp: false,
  multiTp: [],
  useMultiSl: false,
  multiSl: [],
  marginType: BotMarginTypeEnum.isolated,
  leverage: 1,
  futures: false,
  coinm: false,
  useVolumeFilter: false,
  volumeTop: '500',
  volumeValue: VolumeValueEnum.top25,
  baseStep: '1',
  baseGridLevels: '5',
  useActiveMinigrids: false,
  comboActiveMinigrids: '1',
  dcaCondition: DCAConditionEnum.percentage,
  scaleDcaType: ScaleDcaTypeEnum.percentage,
  closeByTimer: false,
  closeByTimerValue: 10,
  closeByTimerUnits: CooldownUnits.minutes,
  useRelativeVolumeFilter: false,
  relativeVolumeTop: '500',
  relativeVolumeValue: VolumeValueEnum.top25,
  feeOrder: true,
  useMaxDealsPerHigherTimeframe: true,
  maxDealsPerHigherTimeframe: '1',
  ignoreStartDeals: false,
  comboTpBase: ComboTpBase.filled,
  dynamicPriceFilterDeviation: '1',
  dynamicPriceFilterPriceType: DynamicPriceFilterPriceTypeEnum.entry,
  dynamicPriceFilterDirection: DynamicPriceFilterDirectionEnum.under,
  pairPrioritization: PairPrioritizationEnum.alphabetical,
  riskSlType: RiskSlTypeEnum.perc,
  riskSlAmountPerc: '2',
  riskSlAmountValue: '10',
  riskUseTpRatio: true,
  riskTpRatio: '1.5',
  riskMaxPositionSize: '-1',
  riskMinPositionSize: '0',
  dynamicArLockValue: true,
  reinvestValue: '50',
  riskReductionValue: '50',
  useRiskReduction: false,
  useReinvest: false,
  startBotPriceCondition: IndicatorStartConditionEnum.gt,
  stopBotPriceCondition: IndicatorStartConditionEnum.gt,
  type: DCATypeEnum.regular,
  useNoOverlapDeals: false,
  minimumDeviation: '1',
  skipBalanceCheck: false,
  dcaVolumeBaseOn: DCAVolumeType.scale,
  dcaVolumeRequiredChange: '5',
  dcaVolumeRequiredChangeRef: DcaVolumeRequiredChangeRef.tp,
  dcaVolumeMaxValue: '-1',
  dcaCustom: [],
  baseOrderPrice: '0',
  useLimitPrice: false,
  hodlHourly: false,
  notUseLimitReposition: false,
  stopStatus: 'closed',
  terminalDealType: TerminalDealTypeEnum.smart,
  importFrom: '',
  useFixedTPPrices: false,
  useFixedSLPrices: false,
  fixedTpPrice: '',
  fixedSlPrice: '',
  comboSlLimit: false,
  comboTpLimit: false,
  useExperimental: false,
  remainderFullAmount: false,
  autoRebalancing: false,
  adaptiveClose: false,
  useStaticPriceFilter: false,
  useCooldown: false,
  useDynamicPriceFilter: false,
  useVolumeFilterAll: false,
  dynamicPriceFilterOverValue: '5',
  dynamicPriceFilterUnderValue: '5',
  useRiskReward: false,
  riskMaxSl: '-100',
  riskMinSl: '0',
  comboUseSmartGrids: false,
  startDealLogic: IndicatorsLogicEnum.and,
  stopDealLogic: IndicatorsLogicEnum.and,
  stopBotLogic: IndicatorsLogicEnum.and,
  startBotLogic: IndicatorsLogicEnum.and,
  startBotPriceValue: '',
  stopDealSlLogic: IndicatorsLogicEnum.and,
  stopBotPriceValue: '',
  closeOrderType: OrderTypeEnum.limit,
  rrSlType: RRSlTypeEnum.indicator,
  rrSlFixedValue: '2',
};

export const COMBO_FORM_DEFAULTS: Readonly<Required<BotFormData['combo']>> = {
  ...DCA_FORM_DEFAULTS,
  startOrderType: OrderTypeEnum.market,
  tpPerc: '5',
  step: '5',
  useTp: false,
  slPerc: '-25',
};

export const GRID_FORM_DEFAULTS: Readonly<Required<BotFormData['grid']>> = {
  topPrice: 0,
  lowPrice: 0,
  levels: 10,
  gridStep: 1,
  budget: 0,
  useOrderInAdvance: false,
  prioritize: 'level' as const,
  profitCurrency: 'quote',
  orderFixedIn: 'quote',
  sellDisplacement: 0,
  gridType: 'geometric',
  tpSl: false,
  tpSlCondition: 'valueChanged',
  tpPerc: 20,
  slPerc: -20,
  tpTopPrice: 0,
  slLowPrice: 0,
  tpSlAction: 'stop',
  slCondition: 'valueChanged',
  slAction: 'stop',
  useStartPrice: false,
  marginType: BotMarginTypeEnum.isolated,
  leverage: 1,
  futures: false,
  coinm: false,
  newProfit: true,
  strategy: StrategyEnum.long,
  futuresStrategy: FuturesStrategyEnum.neutral,
  updatedBudget: true,
  feeOrder: true,
  ordersInAdvance: 6,
  tpSlLimit: false,
  slLimit: false,
  sl: false,
  startPrice: '',
  skipBalanceCheck: false,
};
