import type { ShortcutConfig, ShortcutKey } from '@/stores/shortcutStore';

// Canonical IDs for all shortcuts used across the app
export const SHORTCUT_IDS = {
  // Managers
  ManagerWidgets: 'manager-widgets',
  ManagerLayout: 'manager-layout',
  ManagerDashboard: 'manager-dashboard',
  ManagerShortcuts: 'manager-shortcuts',
  ManagerGlobalSearch: 'manager-global-search',

  // Actions
  ActionNotifications: 'action-notifications',
  ActionChat: 'action-chat',
  ActionToggleTradingMode: 'action-toggle-trading-mode',

  // Panel Controls
  PanelExpandLeft: 'panel-expand-left',
  PanelExpandRight: 'panel-expand-right',
  PanelExpandUp: 'panel-expand-up',
  PanelExpandDown: 'panel-expand-down',

  // Navigation
  NavTradingTerminal: 'nav-trading-terminal',
  NavDashboard: 'nav-dashboard',
  NavTradingBots: 'nav-trading-bots',
  NavComboBots: 'nav-combo-bots',
  NavGridBots: 'nav-grid-bots',
  NavManualBacktesting: 'nav-manual-backtesting',
  NavRulebooks: 'nav-manual-backtesting-strategies',
  NavSettings: 'nav-settings',
  NavPortfolio: 'nav-portfolio',
  NavTrades: 'nav-trades',
  NavJournal: 'nav-journal',
  NavReports: 'nav-reports',
  NavOverview: 'nav-overview',
  NavHedgeDcaBots: 'nav-hedge-dca-bots',
  NavHedgeComboBots: 'nav-hedge-combo-bots',
  NavExchanges: 'nav-exchanges',

  // New-bot creation shortcuts (Shift + bot-type letter)
  NewDcaBot: 'new-dca-bot',
  NewComboBot: 'new-combo-bot',
  NewGridBot: 'new-grid-bot',
  NewHedgeDcaBot: 'new-hedge-dca-bot',
  NewHedgeComboBot: 'new-hedge-combo-bot',
} as const;

export type ShortcutId = (typeof SHORTCUT_IDS)[keyof typeof SHORTCUT_IDS];

// Single source of truth for default shortcuts (without actions)
export const SHORTCUT_DEFAULTS: Omit<ShortcutConfig, 'action'>[] = [
  // Managers (Cmd+... by default)
  // NOTE: Widget Manager and Layout Manager shortcuts were intentionally
  // removed from defaults to consolidate into the unified Dashboard Manager.
  {
    id: SHORTCUT_IDS.ManagerDashboard,
    label: 'Dashboard Manager',
    description: 'Toggle dashboard manager',
    defaultKey: { key: 'd', modifiers: { cmd: true } },
    currentKey: { key: 'd', modifiers: { cmd: true } },
    enabled: true,
    deleted: false,
    category: 'managers',
  },
  {
    id: SHORTCUT_IDS.ManagerShortcuts,
    label: 'Shortcut Manager',
    description: 'Open the Shortcut Manager',
    defaultKey: { key: '/', modifiers: { cmd: true } },
    currentKey: { key: '/', modifiers: { cmd: true } },
    enabled: true,
    deleted: false,
    category: 'managers',
  },
  {
    id: SHORTCUT_IDS.ManagerGlobalSearch,
    label: 'Global Search',
    description: 'Open the Global Search',
    defaultKey: { key: '.', modifiers: { cmd: true } },
    currentKey: { key: '.', modifiers: { cmd: true } },
    enabled: true,
    deleted: false,
    category: 'managers',
  },

  // Actions
  {
    id: SHORTCUT_IDS.ActionNotifications,
    label: 'Notifications',
    description: 'Toggle notifications panel',
    defaultKey: { key: 'i', modifiers: { cmd: true } },
    currentKey: { key: 'i', modifiers: { cmd: true } },
    enabled: true,
    deleted: false,
    category: 'actions',
  },
  {
    id: SHORTCUT_IDS.ActionChat,
    label: 'AI Chat',
    description: 'Toggle AI chat',
    defaultKey: { key: 'k', modifiers: { cmd: true } },
    currentKey: { key: 'k', modifiers: { cmd: true } },
    enabled: true,
    deleted: false,
    category: 'actions',
  },
  {
    id: SHORTCUT_IDS.ActionToggleTradingMode,
    label: 'Toggle Trading Mode',
    description: 'Switch between paper and live trading',
    defaultKey: { key: 'e', modifiers: { cmd: true } },
    currentKey: { key: 'e', modifiers: { cmd: true } },
    enabled: true,
    deleted: false,
    category: 'actions',
  },

  // Panel Controls (arrow keys)
  {
    id: SHORTCUT_IDS.PanelExpandLeft,
    label: 'Push Content Left',
    description:
      'Progressively expand right panel: collapsed → default → fully expanded (Alt+Left)',
    defaultKey: { key: 'ArrowLeft', modifiers: { alt: true } },
    currentKey: { key: 'ArrowLeft', modifiers: { alt: true } },
    enabled: true,
    deleted: false,
    category: 'panels',
  },
  {
    id: SHORTCUT_IDS.PanelExpandRight,
    label: 'Push Content Right',
    description:
      'Progressively collapse right panel: fully expanded → default → collapsed (Alt+Right)',
    defaultKey: { key: 'ArrowRight', modifiers: { alt: true } },
    currentKey: { key: 'ArrowRight', modifiers: { alt: true } },
    enabled: true,
    deleted: false,
    category: 'panels',
  },
  {
    id: SHORTCUT_IDS.PanelExpandUp,
    label: 'Push Content Up',
    description:
      'Progressively expand bottom panel: collapsed → default → fully expanded (Alt+Up)',
    defaultKey: { key: 'ArrowUp', modifiers: { alt: true } },
    currentKey: { key: 'ArrowUp', modifiers: { alt: true } },
    enabled: true,
    deleted: false,
    category: 'panels',
  },
  {
    id: SHORTCUT_IDS.PanelExpandDown,
    label: 'Push Content Down',
    description:
      'Progressively collapse bottom panel: fully expanded → default → collapsed (Alt+Down)',
    defaultKey: { key: 'ArrowDown', modifiers: { alt: true } },
    currentKey: { key: 'ArrowDown', modifiers: { alt: true } },
    enabled: true,
    deleted: false,
    category: 'panels',
  },

  // Navigation (single letters)
  {
    id: SHORTCUT_IDS.NavTradingTerminal,
    label: 'Trading Terminal',
    description: 'Navigate to trading terminal',
    path: '/terminal',
    defaultKey: { key: 't', modifiers: {} },
    currentKey: { key: 't', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavDashboard,
    label: 'Dashboard',
    description: 'Navigate to the main dashboard',
    path: '/dashboard',
    defaultKey: { key: 'd', modifiers: {} },
    currentKey: { key: 'd', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavOverview,
    label: 'Overview',
    description: 'Navigate to the Overview page',
    path: '/overview',
    defaultKey: { key: 'o', modifiers: {} },
    currentKey: { key: 'o', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavTradingBots,
    label: 'Trading Bots',
    description: 'Navigate to trading bots page',
    path: '/bot',
    defaultKey: { key: 'b', modifiers: {} },
    currentKey: { key: 'b', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavComboBots,
    label: 'Combo Bots',
    description: 'Navigate to combo bots page',
    path: '/combo',
    defaultKey: { key: 'c', modifiers: {} },
    currentKey: { key: 'c', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavHedgeComboBots,
    label: 'Hedge Combo Bots',
    description: 'Navigate to Hedge Combo bots',
    path: '/hedge/combo',
    defaultKey: { key: 'w', modifiers: {} },
    currentKey: { key: 'w', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavGridBots,
    label: 'Grid Bots',
    description: 'Navigate to grid bots page',
    path: '/grid',
    defaultKey: { key: 'g', modifiers: {} },
    currentKey: { key: 'g', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavHedgeDcaBots,
    label: 'Hedge DCA Bots',
    description: 'Navigate to Hedge DCA bots',
    path: '/hedge/bot',
    defaultKey: { key: 'h', modifiers: {} },
    currentKey: { key: 'h', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavRulebooks,
    label: 'Rulebooks',
    description: 'Navigate to Rulebooks',
    path: '/rulebooks',
    defaultKey: { key: 'r', modifiers: {} },
    currentKey: { key: 'r', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavManualBacktesting,
    label: 'Manual Backtesting Sessions',
    description: 'Navigate to manual backtesting sessions',
    path: '/manual-backtesting/sessions',
    defaultKey: { key: 'm', modifiers: {} },
    currentKey: { key: 'm', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavSettings,
    label: 'Settings',
    description: 'Navigate to settings page',
    path: '/settings',
    defaultKey: { key: 's', modifiers: {} },
    currentKey: { key: 's', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavPortfolio,
    label: 'Portfolio',
    description: 'Navigate to portfolio page',
    path: '/portfolio',
    defaultKey: { key: 'p', modifiers: {} },
    currentKey: { key: 'p', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavTrades,
    label: 'Trades',
    description: 'Navigate to trades page',
    path: '/trading',
    defaultKey: { key: 'x', modifiers: {} },
    currentKey: { key: 'x', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavJournal,
    label: 'Trade Journal',
    description: 'Navigate to trade journal page',
    path: '/journal',
    defaultKey: { key: 'j', modifiers: {} },
    currentKey: { key: 'j', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavReports,
    label: 'Reports',
    description: 'Navigate to reports page',
    path: '/reports',
    defaultKey: { key: 'q', modifiers: {} },
    currentKey: { key: 'q', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NavExchanges,
    label: 'Exchanges',
    description: 'Navigate to exchanges page',
    path: '/exchanges',
    defaultKey: { key: 'e', modifiers: {} },
    currentKey: { key: 'e', modifiers: {} },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },

  // New-bot creation shortcuts — Shift + the bot's nav letter.
  // Mirrors the navigation defaults (b/c/g/h/w) so the muscle memory
  // is "shift to create, no shift to browse".
  {
    id: SHORTCUT_IDS.NewDcaBot,
    label: 'New DCA Bot',
    description: 'Create a new DCA bot',
    path: '/bot/new',
    defaultKey: { key: 'b', modifiers: { shift: true } },
    currentKey: { key: 'b', modifiers: { shift: true } },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NewComboBot,
    label: 'New Combo Bot',
    description: 'Create a new combo bot',
    path: '/combo/new',
    defaultKey: { key: 'c', modifiers: { shift: true } },
    currentKey: { key: 'c', modifiers: { shift: true } },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NewGridBot,
    label: 'New Grid Bot',
    description: 'Create a new grid bot',
    path: '/grid/new',
    defaultKey: { key: 'g', modifiers: { shift: true } },
    currentKey: { key: 'g', modifiers: { shift: true } },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NewHedgeDcaBot,
    label: 'New Hedge DCA Bot',
    description: 'Create a new hedge DCA bot',
    path: '/hedge/bot/new',
    defaultKey: { key: 'h', modifiers: { shift: true } },
    currentKey: { key: 'h', modifiers: { shift: true } },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
  {
    id: SHORTCUT_IDS.NewHedgeComboBot,
    label: 'New Hedge Combo Bot',
    description: 'Create a new hedge combo bot',
    path: '/hedge/combo/new',
    defaultKey: { key: 'w', modifiers: { shift: true } },
    currentKey: { key: 'w', modifiers: { shift: true } },
    enabled: true,
    deleted: false,
    category: 'navigation',
  },
];

export function getDefaultKey(id: ShortcutId): ShortcutKey | undefined {
  const found = SHORTCUT_DEFAULTS.find((s) => s.id === id);
  return found?.defaultKey;
}
