import type { ReactNode } from 'react';

import { ArrowDownRight, ArrowUpRight, LineChart } from 'lucide-react';

import { Card } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { InfoIcon, Tooltip } from '@/components/ui/tooltip';
import type {
  GridCurrency,
  GridFundsSnapshot,
  GridFundsSnapshotEntry,
} from '@/types/bots/grid';

interface FundsOverviewProps {
  funds?: GridFundsSnapshot;
  currency: GridCurrency;
  formatAmount: (
    value: number,
    options?: { currency?: GridCurrency; maximumFractionDigits?: number }
  ) => string;
}

const changeBadgeClass = (change?: number) => {
  if (typeof change !== 'number' || change === 0) {
    return 'text-muted-foreground';
  }
  return change > 0 ? 'text-success' : 'text-destructive';
};

const ENTRY_TOOLTIPS: Record<string, { text: string; url?: string }> = {
  Invested: {
    text: "The portion of your bot's funds currently locked in grid orders on the exchange.",
  },
  Free: {
    text: 'The portion of profit generated by a grid bot that is readily available in your balance and is not earmarked for re-creating a grid order.',
    url: '/help/free-profit-grid-bots',
  },
  Total: {
    text: 'The present value of your funds managed by the grid bot. This includes any profits or losses incurred since the inception of the bot.',
    url: '/help/initial-current-funds-grid',
  },
  'Bot Profit': { text: "The bot's total realized P&L." },
  'Initial Invested': {
    text: 'The value change of the initial funds at the current rates (i.e. buy and hold extrapolation).',
    url: '/help/initial-current-funds-grid',
  },
};

const renderEntry = (
  entry: GridFundsSnapshotEntry | undefined,
  currency: GridCurrency,
  formatAmount: FundsOverviewProps['formatAmount']
): ReactNode => {
  if (!entry) {
    return <span className="text-muted-foreground">—</span>;
  }

  const { label, value, change, changePercent } = entry;
  const formattedValue = formatAmount(value, {
    currency,
    maximumFractionDigits: currency === 'usd' ? 2 : 6,
  });

  const hint = ENTRY_TOOLTIPS[label];

  return (
    <div className="space-y-1">
      <p className="text-xs uppercase tracking-wide text-muted-foreground flex items-center gap-1">
        {label}
        {hint && (
          <Tooltip tooltip={hint.text} tooltipURL={hint.url} side="top">
            <InfoIcon />
          </Tooltip>
        )}
      </p>
      <p className="text-base font-semibold text-card-foreground">
        {formattedValue}
      </p>
      {(typeof change === 'number' || typeof changePercent === 'number') && (
        <div
          className={`flex items-center gap-1 text-xs ${changeBadgeClass(change)}`}
        >
          {typeof change === 'number' && (
            <span className="font-medium">
              {change > 0 ? '+' : ''}
              {formatAmount(change, {
                currency,
                maximumFractionDigits: currency === 'usd' ? 2 : 6,
              })}
            </span>
          )}
          {typeof changePercent === 'number' && (
            <span className="flex items-center gap-1">
              {changePercent > 0 ? (
                <ArrowUpRight className="h-3 w-3" />
              ) : (
                <ArrowDownRight className="h-3 w-3" />
              )}
              {changePercent > 0 ? '+' : ''}
              {changePercent.toFixed(2)}%
            </span>
          )}
        </div>
      )}
    </div>
  );
};

export const FundsOverview: React.FC<FundsOverviewProps> = ({
  funds,
  currency,
  formatAmount,
}) => {
  if (!funds) {
    return null;
  }

  return (
    <div className="grid gap-md lg:grid-cols-7">
      <Card className="lg:col-span-4 space-y-md border-border/60 bg-card/60 p-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground flex items-center gap-1">
              Current Funds
              <Tooltip
                tooltip="The present value of your funds managed by the grid bot. This includes any profits or losses incurred since the inception of the bot."
                tooltipURL="/help/initial-current-funds-grid"
                side="top"
              >
                <InfoIcon />
              </Tooltip>
            </h3>
            <p className="text-xs text-muted-foreground">
              Balances converted to {currency.toUpperCase()} value
            </p>
          </div>
          <LineChart className="h-5 w-5 text-muted-foreground" />
        </div>
        <div className="grid gap-md sm:grid-cols-2">
          {renderEntry(funds.current.invested, currency, formatAmount)}
          {renderEntry(funds.current.free, currency, formatAmount)}
          {renderEntry(funds.current.total, currency, formatAmount)}
          {renderEntry(funds.current.botProfit, currency, formatAmount)}
        </div>
        {typeof funds.current.breakEvenPrice === 'number' && (
          <div className="rounded-md border border-border/60 bg-background/40 px-3 py-2 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1">
              Break-even price
              <Tooltip
                tooltip="The price at which your initial value equals the current value of the bot."
                tooltipURL="/help/breakeven-price-grid"
                side="top"
              >
                <InfoIcon />
              </Tooltip>
            </span>{' '}
            <span className="font-medium text-card-foreground">
              {formatAmount(funds.current.breakEvenPrice, {
                currency: 'quote',
                maximumFractionDigits: 4,
              })}
            </span>
          </div>
        )}
      </Card>

      <Card className="lg:col-span-3 space-y-md border-border/60 bg-card/60 p-5">
        <div>
          <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground flex items-center gap-1">
            Initial Snapshot
            <Tooltip
              tooltip="The value change of the initial funds at the current rates (i.e. buy and hold extrapolation)."
              tooltipURL="/help/initial-current-funds-grid"
              side="top"
            >
              <InfoIcon />
            </Tooltip>
          </h3>
          <p className="text-xs text-muted-foreground">
            Starting balances and invested capital
          </p>
        </div>
        <div className="grid gap-md">
          {renderEntry(funds.initial.invested, currency, formatAmount)}
          <Separator className="bg-border/40" />
          <div className="grid gap-sm sm:grid-cols-3">
            <div className="space-y-1">
              <p className="text-xs uppercase tracking-wide text-muted-foreground">
                {funds.baseAsset}
              </p>
              <p className="text-base font-semibold text-card-foreground">
                {formatAmount(funds.initial.base.value, {
                  currency: 'base',
                  maximumFractionDigits: 6,
                })}
              </p>
            </div>
            <div className="space-y-1">
              <p className="text-xs uppercase tracking-wide text-muted-foreground">
                {funds.quoteAsset}
              </p>
              <p className="text-base font-semibold text-card-foreground">
                {formatAmount(funds.initial.quote.value, {
                  currency: 'quote',
                  maximumFractionDigits: 6,
                })}
              </p>
            </div>
            <div className="space-y-1">
              <p className="text-xs uppercase tracking-wide text-muted-foreground">
                USD
              </p>
              <p className="text-base font-semibold text-card-foreground">
                {formatAmount(funds.initial.usd.value, {
                  currency: 'usd',
                  maximumFractionDigits: 2,
                })}
              </p>
            </div>
          </div>
        </div>
      </Card>

      {funds.futures && (
        <Card className="lg:col-span-7 grid gap-md border-border/60 bg-card/60 p-5 md:grid-cols-3">
          <div className="space-y-1">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">
              Leverage
            </p>
            <p className="text-lg font-semibold text-card-foreground">
              {funds.futures.leverage ? `${funds.futures.leverage}x` : '—'}
            </p>
          </div>
          <div className="space-y-1">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">
              Notional Value
            </p>
            <p className="text-lg font-semibold text-card-foreground">
              {funds.futures.notionalValue
                ? formatAmount(funds.futures.notionalValue, {
                    currency: 'usd',
                    maximumFractionDigits: 2,
                  })
                : '—'}
            </p>
          </div>
          <div className="space-y-1">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">
              PnL
            </p>
            <p
              className={`text-lg font-semibold ${changeBadgeClass(funds.futures.pnl?.value)}`}
            >
              {funds.futures.pnl
                ? formatAmount(funds.futures.pnl.value, {
                    currency,
                    maximumFractionDigits: currency === 'usd' ? 2 : 6,
                  })
                : '—'}
            </p>
          </div>
        </Card>
      )}
    </div>
  );
};

export default FundsOverview;
